### ISSUE TITLE
cryptic error message is shown when connecting with "tenant" account without "user" set: "Cannot connect to specified cloud, please check the identity and credentials: apiType compute not found in catalog []"

### ISSUE THREAD

**Issue by alexeyOnGitHub** [jenkinsci/openstack-cloud-plugin#10]
I used my "tenant" name and not "user:tenant" in the plugin configuration section on Jenkins | Configure Server page.

got this error message when clicking "Test Connection":

    Cannot connect to specified cloud, please check the identity and credentials: 
    apiType compute not found in catalog []

my endpoint URL: http://api-sfly1.client.metacloud.net:5000/v2.0
Jenkins version: 1.617
Openstack Cloud plugin version: 1.7

it would be nice to notify user that "user:tenant" should be used instead of just "tenant". and also explain the difference if possible...

**Comment by olivergondza** [comment]
Reported as [JENKINS-28789](https://issues.jenkins-ci.org/browse/JENKINS-28789).

**Comment by alexeyOnGitHub** [comment]
great, thank you!
