### ISSUE TITLE
Allow sorting of Cloud Instance Templates

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#100]
It would be very handy if we can sort the cloud instance templates. We have a lot defined and it's hard to jump around to see similar templates defined so thought it would be nice if we can organize them so that the common ones are together.

**Comment by olivergondza** [comment]
Do you mean manual sorting using drag and drop?

**Comment by zxiiro** [comment]
Yes. unless you can think of a better way to allow organizing the instances into groups.
