### ISSUE TITLE
Volumes are not deleted when an a node is deleted.

### ISSUE THREAD

**Issue by remzix** [jenkinsci/openstack-cloud-plugin#102]
Whenever a node is deleted from Jenkins the OpenStack plugin should terminate the instance and also expected it to delete its attached volume.
We noticed this does not happen as the attached volumes are not deleted. This causes the cluttering of the OpenStack project quota.
Is there any option to do this? I could not find a way to do this via the configuration page (Manage Jenkins).

**Comment by olivergondza** [comment]
Hi, the plugin does not anything to attach any volumes. Can you elaborate on your use case? What kind of volumes? How do you attache them?

**Comment by remzix** [comment]
We use the plugin to create OpenStack instances from an image (image ID used for slave template). Each of the instances gets its own volume attached (cloned from the image).
When we delete a slave, the plugin terminates the instance but the volume that was attached to that instance is not deleted and remains unattached.
This causes the OpenStack project's Volume Storage to be filled with unallocated volumes which have to be manually deleted.

When i **manually** create an instance from image - the "Boot from image (creates a new volume)" option - in the Horizon dashboard, i see there's a checkbox for the "Delete on Terminate" option. If i enable this checkbox, the volume will be deleted automatically when the instance is terminated.

Can we achieve the same behaviour via the OpenStack plugin?

**Comment by olivergondza** [comment]
@remzix, When I provision via plugin it never creates a volume. What you describe surely seems like "Boot from image (creates a new volume)" behavior instead of plain old "Boot from image" I rely on. Is that desirable for you - to create a new volume for every slave?

**Comment by remzix** [comment]
@olivergondza thanks for the info. we noticed that we did not use the `delete_on_termination:true` option in our image. it now works.
closing this as not a plugin issue.

**Comment by DEvil0000** [comment]
Thanks, had the same issue.

**Comment by tstrul1** [comment]
@remzi-e Where did you change this setting? I cant find it anywhere in image options/metadata

**Comment by joinghel** [comment]
@remzi-e @DEvil0000 How can this be configured? I tried adding `delete_on_termination:true` to the metadata of my image, but the save button is disabled in Horizon.

**Comment by glothriel** [comment]
@DEvil0000 @remzi-e @joinghel @tstrul1 Did anyone of you solve the issue, if so, how? Setting this option in image metadata does not seem to fix the problem.

**Comment by joinghel** [comment]
@glothriel in our image metadata:

![image](https://user-images.githubusercontent.com/22074706/92901618-e79a4780-f420-11ea-8c6d-20bd94866c50.png)

we added or adapted (I don't remember): `block_device_mapping`:
 
`[{"guest_format": null, "boot_index": 0, "delete_on_termination": true, "no_device": null, "snapshot_id": "cca35882-d038-4798-abdc-b6b70c17af2c", "device_name": "/dev/vda", "disk_bus": "virtio", "image_id": null, "source_type": "snapshot", "tag": null, "device_type": "disk", "volume_id": null, "destination_type": "volume", "volume_size": 60}]`

The important part is: `"delete_on_termination": true`.
