### ISSUE TITLE
Only administrator is able to provision a node on /computer/ page

### ISSUE THREAD

**Issue by olivergondza** [jenkinsci/openstack-cloud-plugin#105]

**Comment by olivergondza** [comment]
This seems to be a problem in core that goes as deep as https://github.com/jenkinsci/jenkins/commit/8d771bc2.

**Comment by olivergondza** [comment]
Proposing fix to core: https://github.com/jenkinsci/jenkins/pull/2521

**Comment by andyuk1986** [comment]
Proposed fix to plugin as a temporary solution (as discussed with Oliver): #106

**Comment by olivergondza** [comment]
Until this is fixed in core, plugin accept `Item.CONFIGURE` permission to provision nodes manually. Once the plugin starts to depend on a core version with a fix, this workaround will be removed.
