### ISSUE TITLE
"Creating a new JClouds Slave" is blocking Jenkins initialization

### ISSUE THREAD

**Issue by alexeyOnGitHub** [jenkinsci/openstack-cloud-plugin#11]
using Jenkins 1.618 on Ubuntu 14.

I see this in /var/log/jenkins/jenkins.log:

    Jun 29, 2015 5:14:30 PM jenkins.plugins.openstack.compute.JCloudsSlave createComputer
    INFO: Creating a new JClouds Slave

and Jenkins seems to be stuck with this... 
I suppose this will be unblocked eventually, but I think this should not prevent Jenkins UI from loading...

**Comment by olivergondza** [comment]
This does not imply openstack plugin is the reason why your Jenkins seems hung. Take the [thread dump](https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump) to know for sure.

**Comment by alexeyOnGitHub** [comment]
I'll get back to my experiments with this plugin and I'll check it soon.

**Comment by olivergondza** [comment]
Closing until there is some evidence it is openstack plugin problem...
