### ISSUE TITLE
NullPointerException when saving system config

### ISSUE THREAD

**Issue by seanf** [jenkinsci/openstack-cloud-plugin#110]
Jenkins version: 1.651.3
OpenStack Cloud Plugin version: 2.11

I'll attach the stack trace separately.

**Comment by seanf** [comment]
Stack trace showing NullPointerException in `/configure`:
[jenkins.log.txt](https://github.com/jenkinsci/openstack-cloud-plugin/files/489056/jenkins.log.txt)

**Comment by olivergondza** [comment]
thanks for reporting this, it is an obvious bug.

**Comment by seanf** [comment]
Thanks @olivergondza
