### ISSUE TITLE
Provisioning of several slaves with the same label for different jobs

### ISSUE THREAD

**Issue by iamanikeev** [jenkinsci/openstack-cloud-plugin#113]
Hi! This is more a question than an issue. We have the following problem: instance number is set to 10 in global configuration; one label is configured for two different jobs. When these two jobs are ran at the same time, only one slave instance is being provisioned, first job starts immediately, and the second one waits for the slave to become vacant. That doesn't seem to be a default behavior, is it? 
P.S: We are running quite an old version of plugin (2.0), because keystone v3 is not available in newer version, and there is a [2.0 fork](https://github.com/monkeylittleinc/openstack-cloud-plugin) with that problem fixed. If the underlining problem is fixed in > 2.0 versions, I will try to make a pull request with backward-compatible support for v3.

**Comment by olivergondza** [comment]
I am afraid this is how Jenkins provisioning works. The approach to provisioning is a bit more conservative than *launch X machines for X builds in queue*. Check your Jenkins logs for "excess workload" messaged explaining how much nodes Jenkins thinks it needs based on projected future load - I expect it will be `EW < 1`. To my understanding Jenkins tries to take past load into account so in case of abrupt spikes less nodes is used but the number of machines should balance with the current load eventually. The reason behind this, I presume, is not to waste resources you likely pay for in case there is a chance some machine will get freed soon.

---

Ad Keystone v3, it is tracked in https://github.com/jenkinsci/openstack-cloud-plugin/pull/93. The struggle is to keep the plugin compatible with v2 at the same time. Contribution welcome.
