### ISSUE TITLE
the limit on the creation of slaves is cumulative within different masters

### ISSUE THREAD

**Issue by carlobongiovanni** [jenkinsci/openstack-cloud-plugin#122]
Hi, first of all congratulations for the plugin ;)

now to the problem: I have a setup in which I want to run more jenkins masters on the same openstack tenant. I initially setup the limit on the slaves number to 10, and then I realized that the second master could not allocate new slaves, saying that the threshold had been reached. 

Why is this so? I was expecting that each master could create/manage their own number of slaves. 

Thanks,best
C.

**Comment by olivergondza** [comment]
There are 2 limits to reach: the limit you configure in Jenkins (and you have reasonably polite log message about it) or openstack tenant limit. Which one do you observe?

**Comment by olivergondza** [comment]
Closing this for lack of response.
