### ISSUE TITLE
Default JDK for slave.jar execution

### ISSUE THREAD

**Issue by mhermosi** [jenkinsci/openstack-cloud-plugin#126]
Why the plugin when trying to identify default java does not use the global JDK definition?
in my case I have configured jdk1.8.0_112 but slave is running on Installing jdk-7u80

**Comment by olivergondza** [comment]
Note that the JDKs installations in global configuration are for builds, the plugin locates/downloads JDK to run the agent itself. It might be worth extending the plugin to check the JDK installations locations except for the hardcoded before giving up and downloading but it would only work for "preinstalled tool installations". If the JDK is configured to be downloaded on-demand, it require running agent to do so but we are about to start it - chicken and egg.

Is this causing you some problems or its just surprising?

**Comment by mhermosi** [comment]
Oh, yes I understand that JDK install in global are for builds, but, it would be nice to have something similar to setup a desired version of Java to run the slaves

I was just curious about that

**Comment by olivergondza** [comment]
Sure, would path to preferred java home in template/cloud configuration work for you?

**Comment by mhermosi** [comment]
I’m looking at this moment ways to configure the open stack instance initialization to customize there the java to be installed.

so, at the moment unveiling how to put some cloud-init script in the plugin.

Thanks,

Martin Hermosilla G.
mhermosi@gmail.com
+1 (650) 603-0640
+ (56) 2 2979-0072

**Comment by sbaier1** [comment]
@olivergondza either environment variables to set upon slave startup (like with static jenkins slaves) or preferred java home configuration would be a great idea

**Comment by olivergondza** [comment]
Coincidentally, #176 released 2 days ago provides an ability for slave options to specify path to java.
