### ISSUE TITLE
Add support for static ips

### ISSUE THREAD

**Issue by minz1027** [jenkinsci/openstack-cloud-plugin#147]
We are not using floating-ips and will get 403 for anything related to floating ips.
Thus we are having problems deleting the instances since it will do a floating ip list first.
https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L324

Can anyone help with this? Make floating ip  configurable?

**Comment by olivergondza** [comment]
The feature is not there. Please watch #128 for progress.
