### ISSUE TITLE
Stagger cloud spinups

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#151]
It would be nice if there was a feature to tell Jenkins to spin up additional resources slowly. We sometimes have 100 jobs that queue and Jenkins might try to handle it by immediately spinning up many servers simultaneously. I think a feature that you could tell it to spin up x number of servers and wait y minutes before adding additional capacity would be useful.

**Comment by olivergondza** [comment]
The pace on which nodes are provisioned is handled by heuristics from Jenkins core based on label load statistics. This causes sometime nodes are not provisioned eagerly enough and sometime they are provisioned too eagerly. I presume there might be a way to finetune it from plugin but I would like to see how to represent the expected provisioning pace first.

There are situations when users want the machines to be launched ASAP: PR build or build scheduled manually while user is waiting staring at the UI. On the other hand, when you fill your queue so it will be processed over weekend, maxing out the resources to have all results by Sunday morning makes little sense.

---

What are you trying to achieve by delaying the provisioning by several minutes? Let's say those 100 builds take an hour to complete and the plugin would wait 5 minutes after provisioning 10% of required nodes. It will still provision 100 nodes eventually but some builds will wait 50 minutes in queue for no reason. No resources saved, time needed to process the load is 190% compared to eager approach. Of course you can finetune that to batter suite this particular load but I am trying to demonstrate that perhaps no value would work well when build time, queue length and users' will to wait for build to complete is varying on every instance.

---

I am thinking of applying a load factor to make the bulks of machines provisioned at once proportional to the maximum instance limit. So it will be provisioned more eagerly when there is a small load (chances that matching node gets freed soon is small / not that much resources squandered) and less eager when the load is high (chances are that freed node will be reused are higher, large matrix does not take whole openstack with it right away, etc.)

There are also other things we can take advantage of like executors that are likely soon to be freed based on estimated time of current build, etc. Though all this makes the plugin more complicated to both maintain and comprehend by users - and reasoning about "why no nodes are provisioned when there are builds in my queue" even harder.

I am opening this to brainstorming so the more real world use-cases we hear of, the better.

**Comment by zxiiro** [comment]
Ah I could have sworn I opened this ticket before but forgot about #103 

The problem we keep running into on an almost daily basis now is that we use openstack-cloud-plugin to spin up 1 server to run a job as the control vm. The inside of that job we use Heat to spin up a lab to run our CSIT testing against. However when a large queue suddenly appears with like 100 queued jobs openstack cloud plugin will provision the max amount of control servers instantly then in each one of those jobs it hammers the Rackspace API at the same time and Rackspace throws API errors at us. We could mitigate this if we could control how quickly the servers are deployed simultaneously.

Another idea I have is to setup a random API timer in each job so that they don't all hit the API at the same time but even a random timer on independent machines can sometimes line up just right I think.

**Comment by olivergondza** [comment]
Idea: define a max number of nodes to be in provisioning state at the same time. This way we will avoid configuring magic timeouts and the plugin will figure it out based on how fast nodes gets provisioned.

**Comment by zxiiro** [comment]
This would work for me too.

**Comment by Alvarus** [comment]
Hello. We're run into similar problem to the one described.
We sometimes have a lot of jobs arriving simultaneously, and Jenkins starts provisioning a lot of nodes, way more then is set as Maximum for the cloud or even set in Openstack Project limits. Openstack spins up as many as it can, returning an error to Jenkins for the rest.
I often see 12-15 nodes being spinned up, while in the plugin maximum is set to 8. Cloud Statistics page then looks angry red.

As I understood, plugin is getting the number of nodes from openstack. But since provisioning is done asyncronously and it takes some time for openstack to create the node, it can request several times more nodes than it should before openstack creates the first one.

Perhaps, taking into account the number of nodes already requested would make it more accurate?

**Comment by olivergondza** [comment]
The provisioning throttling is implemented in #368.
