### ISSUE TITLE
Do not create duplicate desposer items for the same server

### ISSUE THREAD

**Issue by olivergondza** [jenkinsci/openstack-cloud-plugin#168]
It seems that `JCloudsCleanupThread` converts running servers into disposables every time it founds some. For locked servers, for instance, this can keep adding them forever.

**Comment by winklerm** [comment]
@olivergondza thanks for finding it!

**Comment by olivergondza** [comment]
Depends on resource-disposer-0.8[1] (yet to be released).

[1] https://github.com/jenkinsci/resource-disposer-plugin/commit/f7d0c3cc3e236454ff5b2987c50cadcbf46255a1
