### ISSUE TITLE
unable to choose a snapshot in image list

### ISSUE THREAD

**Issue by webczat** [jenkinsci/openstack-cloud-plugin#178]
I use ovh public cloud, and it is compatible with open stack.
Because windows images there do not support cloud init, I have created my vm where I have installed cloudbase init, then shut it down and taken a machine snapshot, and this snapshot appears in the "openstack image list".
However, image selection in jenkins shows only public images, does not show my snapshot at all, and it is not possible to select it nor to type it's id or name or to do whatever.

**Comment by olivergondza** [comment]
I have no experience with or access to the stack you mention. Ware you able to verify by some other kind of openstack client that the snapshots are listed? Like the console tools (`nova`/`glance`.? Can you compare the attributes with some of the working image like visibility / sharing (if applicable)?

**Comment by webczat** [comment]
not sure if sharing is supported by that api version, but visibility is
private.
As I said before, it is listed by "openstack list image", "openstack" is
a new style command line client replacing nova/glance/whatever, I see it
and was able to use it few times, and the jclouds plugin sees it.
However jclouds plugin seems to have other problems.

**Comment by webczat** [comment]
I have just noticed that even some public images are not displayed. like probably mostly/only those used for gpu instances, but I believe (from what I read in the code) that they should be displayed provided that they are not filtered based on any criteria. Not sure if that is a plugin bug, openstack4j bug, or what.

**Comment by webczat** [comment]
Okay, I know what's going on. The plugin probably does not actually apply the set region name, that is:
When creating an "Openstack" instance, the OSClient object is build, and the useRegion method is called on it, but from what I realized, this client is not used for anything, except that the access token is retrieved from the instance and stored, however the token does not contain any info about used regions.
Then, when the openstack plugin wants to use the client for anything, it retrieves it using a ClientProvider object containing the token, the new instance is always created with OSClientFactory.clientFromAccess, but useRegion is not called on it, and region is not really applied anywhere while doing actual api calls.

**Comment by olivergondza** [comment]
@webczat, spot on! Will be part of next release.
