### ISSUE TITLE
One off slaves not getting deleted.

### ISSUE THREAD

**Issue by hathoward** [jenkinsci/openstack-cloud-plugin#18]
Jobs set for one off openstack slaves sit in offline purgatory indefinitely.

Poking around source it looks like:
 openstack-cloud-plugin/openstack-cloud/src/main/java/jenkins/plugins/openstack/compute/JCloudsOneOffSlave.java

does not set 'isPendingDelete' to true.

Submitted pull request as possible fix:
https://github.com/jenkinsci/openstack-cloud-plugin/pull/19

**Comment by olivergondza** [comment]
Closing as #19 was replaced by #36.
