### ISSUE TITLE
increase timeout for server building

### ISSUE THREAD

**Issue by webczat** [jenkinsci/openstack-cloud-plugin#181]
Hello.

It seems that the timeout for server building should probably be increased or configurable.
In my case creating a server may take few minutes or more, and actually, the reason is that I am using a private base image, and it sometimes takes quite long.
Also, in case a timeout is hit, the server should be deleted, the problem is that I hit a timeout today but the server was still there, building.

**Comment by olivergondza** [comment]
Do you have an exception of where this timed-out specifically? It is strange this would not clean the machine - it should after a little while in the worst case.

Note that the timeout of the whole boot-launch cycle is already configurable via *Startup Timeout*.

**Comment by olivergondza** [comment]
Closing as inactive, feel free to reopen with requested info.

**Comment by olivergondza** [comment]
Closing as inactive, feel free to reopen with requested info.
