### ISSUE TITLE
Plugin does not support v2 Glance API

### ISSUE THREAD

**Issue by shayharush** [jenkinsci/openstack-cloud-plugin#182]
Plugin does not support v2 Glance API.  Only deprecated v1 API is supported by Cloud plugin. 
In Ocata (+)  release v1 is deprecated and in most installations is disabled. 
When tried to retrieve image list in Jenkins, no images were found. After enabling v1 API in Glance, images showed up.

**Comment by JGroselle** [comment]
Hi,

I'm affected too. Impossible to retrieve images.
OS version: Ocata
Glance API version: v2

**Comment by olivergondza** [comment]
Please use https://github.com/jenkinsci/openstack-cloud-plugin/issues/77 to track this.
