### ISSUE TITLE
Can't specify a tenant name with ":"

### ISSUE THREAD

**Issue by twillouer** [jenkinsci/openstack-cloud-plugin#183]
Hi,

my tenant name contain a ":".
So the parsing here https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/src/main/java/jenkins/plugins/openstack/compute/internal/Openstack.java#L117 don't permit me to use the plugin.

any workaround or solution ?

**Comment by rds13** [comment]
👍

**Comment by olivergondza** [comment]
Will be addressed by https://github.com/jenkinsci/openstack-cloud-plugin/pull/165

**Comment by olivergondza** [comment]
Fixed

**Comment by twillouer** [comment]
@olivergondza thanks ! any idea for the release date ?

**Comment by olivergondza** [comment]
Fixed in 2.30.

**Comment by twillouer** [comment]
thanks !
