### ISSUE TITLE
Unable to retrieve image list

### ISSUE THREAD

**Issue by balous** [jenkinsci/openstack-cloud-plugin#185]
Hi,

I've built master version of this plugin (commit ID e910153d15735a99f45aaa0736835bae87d2f107) because of unreleased #165. The plugin works fine except of one thing - it is unable to retrieve list of available images from the OS cloud. I had to create the template with unspecified image and than manually edit Jenkin's config.xml and insert image's ID into ```bootSource``` field:
```
...
             <slaveOptions>
               <bootSource class="jenkins.plugins.openstack.compute.slaveopts.BootSource$Image">
                 <name>3507a97d-c6bd-4324-90a2-c59ef9790105</name>
               </bootSource>
...
```
 The plugin than complains that the image doesn't exist:

![image](https://user-images.githubusercontent.com/11254614/34813846-c6a80514-f6ab-11e7-8ea4-1954b2f2cede.png)

I've tried to use Jenkins OS identity to retrieve image list by ```openstack image list``` command and it did work.

**Comment by olivergondza** [comment]
Could it be you openstack uses glance version 2 as in https://github.com/jenkinsci/openstack-cloud-plugin/issues/77?

**Comment by balous** [comment]
Yes, we've got glance-api version 2:14.0.0-0ubuntu1~cloud0 and use v2 api.

**Comment by olivergondza** [comment]
Please track that issue than.
