### ISSUE TITLE
How to instantiate a BootSource image in groovy?

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#186]
Trying to write a Groovy script for this plugin but I'm having trouble figuring out how to create a boot source in Groovy code. Here are some of the things I tried:

```
jenkins.plugins.openstack.compute.slaveopts.BootSource;
def bs = new BootSource.Image("test")


groovy.lang.MissingPropertyException: No such property: BootSource for class: Script1
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
	at Script1.run(Script1.groovy:3)

```
```
jenkins.plugins.openstack.compute.slaveopts.BootSource.Image;
def bs = Image("test")

groovy.lang.MissingMethodException: No signature of method: Script1.Image() is applicable for argument types: (java.lang.String) values: [test]
Possible solutions: main([Ljava.lang.String;), wait(), any(), isCase(java.lang.Object), wait(long), getAt(java.lang.String)
```

Hoping to get a bit of direction from some experts. I was just using the Jenkins script console to run these scripts.

**Comment by olivergondza** [comment]
Have you omitted the keyword `import` at the beginning of those 2 samples when copying or you are running it without it? If it is not there, you are not importing anything and therefore groovy rightfully complains (using some create messages, though) as it does not know the classes you are trying to instantiate.
