### ISSUE TITLE
Document JNLP needs user to provide a script to connect

### ISSUE THREAD

**Issue by mitchellmaler** [jenkinsci/openstack-cloud-plugin#190]
Hello, 

I have a volume snapshot with Windows installed and I am trying to start the slave with JNLP. The agent is spawned in Openstack but then it never connected back to the master. I am not 100% sure if the JNLP agent is being installed and started up and not sure how to debug that issue. Right now it just times out and recreates a new instance.

**Comment by olivergondza** [comment]
Hey, this has to be investigated on OpenStack side (instance console log) or on the machine side as from principle masters just waits for agent to connect. Was the process started? Is it sill running? What was its output?

**Comment by mitchellmaler** [comment]
I looked in the LOG for the instance and I do not see anything in there for the JNLP or agent/slave install. I logged into the instance and I cannot find the agent jar or service being started. I do not think it is downloading and starting the jnlp agent at all.

**Comment by mitchellmaler** [comment]
And maybe I am missing something. In the configuration I select JNLP and that is it. 
Is there a place I have to provide the script for it to install and run the JNLP agent or is that done automatically?

**Comment by mitchellmaler** [comment]
Okay I completely missed the User Data options. It didn't really specify that is what I needed to setup to run JNLP init-script in the documentation.

**Comment by olivergondza** [comment]
Good point, I am reopening this to update the docs.
