### ISSUE TITLE
Build agent instances terminated after 1 hour

### ISSUE THREAD

**Issue by rjbwtr** [jenkinsci/openstack-cloud-plugin#207]
Hi,

Since upgrading to openstack-cloud 2.35 from 2.29 we're noticing that all build agents which aren't configured to be retained indefinitely get terminated after around 1 hour and 10 minutes, regardless of configured retention time.

I can't see anything obvious in the logs. I can only speculate that it's getting terminated in the background and then the cleanup thread is subsequently noticing the termination and cleaning up the instances because they no longer exist.

```
Started OpenStack slave cleanup
Jun 21, 2018 4:43:45 PM FINE jenkins.plugins.openstack.compute.internal.Openstack debug
Openstack client created for "https://openstack.our-org.com:5000/v3", "jenkins:jenkins_user:default", ..., "RegionOne".
Jun 21, 2018 4:43:46 PM WARNING jenkins.plugins.openstack.compute.JCloudsCleanupThread terminatesNodesWithoutServers
No OpenStack server running for computer build-agent-3910. Terminating.
Jun 21, 2018 4:43:46 PM INFO jenkins.plugins.openstack.compute.JCloudsComputer deleteSlave
Deleting slave build-agent-3910
```
Instances appear to be being created with the appropriate retention time and I can't see anything else in the logs that points to why they'd be being deleted after this amount of time.

Rolling back doesn't seem to fix this issue. It's a huge problem for us because builds are being killed mid-way through.

If there's anything else I can do in order to dig deeper into this and provide more information, please let me know.

**Comment by olivergondza** [comment]
> No OpenStack server running for computer build-agent-3910. Terminating.

Suggests OpenStack servers are not running. In theory, It can be accidentally deleted by the plugin because of a bug somewhere. Are there any other logs relevant to those servers? Anything that would indicate machine is deleted? Also, can you verify the servers are not deleted by some other way?

**Comment by olivergondza** [comment]
FTR, the plugin should be able to handle that provided they have different Jenkins URL configured. Otherwise they would step on each other's toes.
