### ISSUE TITLE
Question about missing openstack4j 3.1.1-jenkins2 dependency

### ISSUE THREAD

**Issue by thorntonryan** [jenkinsci/openstack-cloud-plugin#222]
Hello,

I'm not able to build 2.38-2.40 from source due to a missing dependency on `3.1.1-jenkins2`.

https://github.com/jenkinsci/openstack-cloud-plugin/blob/ff41fa98e713841d4dd8bdefa5cc81c373dd4e8c/pom.xml#L28

Looks like the fork was added back in https://github.com/jenkinsci/openstack-cloud-plugin/commit/64f7078fc5dee7904bb9fc401c3391a5601c8ee1

In the past, I've had to rebuild
https://github.com/olivergondza/openstack4j/blob/okhttp-hotfix-release/pom.xml

Where can I find `3.1.1-jenkins2` ?

Thanks,
Ryan

**Comment by olivergondza** [comment]
Good question, I am finally documenting it here: https://github.com/jenkinsci/openstack-cloud-plugin/commit/aaeef83bd59d1d4786d727924c15fff593d5880f

**Comment by thorntonryan** [comment]
Thanks @olivergondza !
