### ISSUE TITLE
Provision node via openstack cloud plugin always proposes nodes only for the first cloud

### ISSUE THREAD

**Issue by tgatinea** [jenkinsci/openstack-cloud-plugin#227]
I've upgrade the Openstack Cloud plugin from 2.37 to 2.40

I had 3 clouds declared in Jenkins system management, with different templates per clouds.

With plugin 2.37 I was able to provision manually new nodes through the Jenkins node management window.

Now, with the plugin 2.40, I still see my 3 clouds in the Jenkins node management window, but for each of them, the nodes that are proposed are the nodes of the templates declared for the first cloud declared in the configuration.

Moreover, I have setup the minimum number of slaves > 0 for the templates of my third cloud in the Openstack system management configuration, but Openstack cloud plugin does not start them.

So I have to rollback to version 2.37

**Comment by olivergondza** [comment]
Thanks for reporting the manual provisioning problem. Please report "minimum number of slaves" problem separately as it is unrelated.

**Comment by tgatinea** [comment]
Concerning the "minimum number of slaves" problem, this was due to an issue in my configuration.

**Comment by tgatinea** [comment]
I've recompiled the plugin with the file src/main/resources/jenkins/plugins/openstack/compute/JCloudsCloud/computerSet.jelly of release openstack-cloud-2.37 and the behavior is correct (Meaning that the templates are well associated to the cloud).

With last version of the file, ${it.templates} and ${it.name} in the section <script>...<script/> refers to the last cloud defined in the list.

**Comment by olivergondza** [comment]
Fixed in #228

**Comment by tgatinea** [comment]
@olivergondza Do you know when you will create a new release for this plugin that will include the correction of this issue?
Thanks by advance

**Comment by olivergondza** [comment]
Good ping, releasing 2.42 right now. Should be in update centers in a couple of hours.
