### ISSUE TITLE
Openstack cloud slave node can not be relaunch with automatically after restart jenkins

### ISSUE THREAD

**Issue by betull** [jenkinsci/openstack-cloud-plugin#234]
After restart Jenkins, Openstack cloud slave node can not be relaunch with automatically. Slave node can be started when manually trigger relaunch ssh node. 
There is below jenkins log for this issue. 

Feb 18, 2019 11:01:24 AM OFF hudson.model.AsyncPeriodicWork$1 run Started OpenStack slave cleanup
Feb 18, 2019 11:01:24 AM SEVERE hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
A thread (OpenStack slave cleanup thread/185) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.

**Comment by olivergondza** [comment]
Please attach the body of the exception thrown so we can investigate.

**Comment by betull** [comment]
[openstack cloud node issue.txt](https://github.com/jenkinsci/openstack-cloud-plugin/files/2875890/openstack.cloud.node.issue.txt)
