### ISSUE TITLE
After restart Jenkins, Openstack cloud slave node can not be relaunch with automatically

### ISSUE THREAD

**Issue by betull** [jenkinsci/openstack-cloud-plugin#235]
After restart Jenkins, Openstack cloud slave node can not be relaunch with automatically. Slave node can be started when manually trigger relaunch ssh node.
There is below jenkins log for this issue.

Feb 18, 2019 11:01:24 AM OFF hudson.model.AsyncPeriodicWork$1 run Started OpenStack slave cleanup
Feb 18, 2019 11:01:24 AM SEVERE hudson.init.impl.InstallUncaughtExceptionHandler$DefaultUncaughtExceptionHandler uncaughtException
A thread (OpenStack slave cleanup thread/185) died unexpectedly due to an uncaught exception, this may leave your Jenkins in a bad way and is usually indicative of a bug in the code.

**Comment by betull** [comment]
[openstack cloud node issue.txt](https://github.com/jenkinsci/openstack-cloud-plugin/files/2875892/openstack.cloud.node.issue.txt)

**Comment by olivergondza** [comment]
That is indeed an interesting error. Some investigation steps:

- Is there IPv6 involved (on master, openstack endpoints, VMs)?
- Where is the "controller" string coming from (anything in cloud config, endpoint URLs)?
- Can you attach `$JENKINS_HOME/nodes/$NODE_NAME/config.xml` for some of the affected nodes?

**Comment by olivergondza** [comment]
Is there any update?

**Comment by betull** [comment]
I solved issue with add jenkins master public ssh key to slave nodes authorized_keys file. Thank you.
