### ISSUE TITLE
Unexpected exception encountered while provisioning agent

### ISSUE THREAD

**Issue by tgatinea** [jenkinsci/openstack-cloud-plugin#242]
We have some issue when Jenkins wants to create slaves.
It is not always the case, but it happens frequently.
The behavior is the following:
- VM are actually created in openstack but the floating IP is not associated to the VM and we have to manually delete these VMs to release the ressources
- We have floating IP in openstack that are actually reserved but not active (e.g. kind of orphan floating IP)
- The Jenkins logs shows a lot of error "Unexpected exception encountered while provisioning agent" with "jenkins.plugins.openstack.compute.internal.Openstack$ActionFailed: timeout Allocating for" (See Attached trace)

Note that we have scripted some openstack commands to "simulate" the plugin jenkins behavior (It creates a VM, creates a floating IP and associates the floating IP to the VM). We have looped on such scenario, but we never reproduced the issue.

Of course, I guess that this kind of scenario does not use the same command as openstack4j does.

Anyway, I'm wondering whether it was possible to make some change on timeout values at:

    '''public @Nonnull FloatingIP assignFloatingIp(@Nonnull Server server, @CheckForNull String poolName) throws ActionFailed {
        debug("Allocating floating IP for " + server.getName());
        ComputeFloatingIPService fips = clientProvider.get().compute().floatingIps(); // This throws when user is not authorized to manipulate FIPs
        FloatingIP ip;
        try {
            ip = fips.allocateIP(poolName);
        } catch (ResponseException ex) {
            // TODO Grab some still IPs from JCloudsCleanupThread
            throw new ActionFailed(ex.getMessage() + " Allocating for " + server.getName(), ex);
        }'''

If you have some suggestion of code modification, I may recompile the plugin and make some tests.

[jenkins.log](https://github.com/jenkinsci/openstack-cloud-plugin/files/2915695/jenkins.log)

**Comment by olivergondza** [comment]
From the log it is apparent you are running into this situation during both server boot and FIP allocation. I am not convinced this is in any way related to the FIPs your tenant has allocated as the cause here is socket read timeouts. As this does not appear to be configured by openstack4j nor this plugin so I believe you are running out of 10 second per openstack request[1].

Here[2] is a patched 2.42 with the 20s timeout hardcoded. If you can get that deployed and you experience improvement, we will have the cause confirmed. Then we can proceed with making this configurable for cases like this.

[1] https://github.com/square/okhttp/blob/cd0c8188a2f7aed6ecaeea8edafb2770981c63c1/okhttp/src/main/java/okhttp3/OkHttpClient.java#L476-L478
[2] https://github.com/olivergondza/openstack-cloud-plugin/commit/8d81d2d993564601f307e977004380b8a7145699

**Comment by inka** [comment]
Hi @olivergondza,

I have seen the same problem a lot in the past weeks and deployed your olivergondza@8d81d2d patch. This helps here to avoid timeouts. I would really appreciate if you for now can merge the hardcoded increase and later can make that configurable somewhere.

The only thing which is left over as error in the stats page is now this but thats probably not related to the discussed timeout:
`java.util.NoSuchElementException: No such server running: e8095c97-14d6-4526-8e01-e871a3bc7f1d
	at jenkins.plugins.openstack.compute.internal.Openstack.getServerById(Openstack.java:480)
	at jenkins.plugins.openstack.compute.JCloudsSlave.getPublicAddressIpv4(JCloudsSlave.java:290)
	at jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$SSH.isWaitingFor(LauncherFactory.java:176)
Caused: jenkins.plugins.openstack.compute.JCloudsCloud$ProvisioningFailedException: No such server running: e8095c97-14d6-4526-8e01-e871a3bc7f1d
	at jenkins.plugins.openstack.compute.slaveopts.LauncherFactory$SSH.isWaitingFor(LauncherFactory.java:178)
	at jenkins.plugins.openstack.compute.JCloudsCloud.slaveIsWaitingFor(JCloudsCloud.java:319)
	at jenkins.plugins.openstack.compute.JCloudsSlaveTemplate.provisionSlave(JCloudsSlaveTemplate.java:215)
	at jenkins.plugins.openstack.compute.JCloudsCloud$NodeCallable.call(JCloudsCloud.java:310)`

Thanks for your great work here!

**Comment by olivergondza** [comment]
@inka, thanks for confirmation. The outstanding exception is likely caused by the `Server` not being found during agent launching for which I have no explanation. As a followup investigation, consult the server log for the VM id and name.

@tgatinea, Can you confirm?

**Comment by tgatinea** [comment]
I was busy these last days. 
I'll come back to this issue next week.
Anyway, thanks both of you for your answers.

**Comment by tgatinea** [comment]
I've tested the patch 10s to 20s:
- 3 clouds with new image created in glance
- 112 slaves that were deleted and re-created using the new image

Note that when the image is new in glance, it takes some time (e.g. Spawning) to be replicated in hosts and it increases the issue.

I've checked that the delete was correct (Before, it often happens that agents were deleted from Jenkins point of view, while it was remaining alive in Openstack). 
=> The patch seems to improve that

During the creation of new slaves I had few issues. Less that before, but still some issues.
And if I set the retention time to 0, I have seen on one cloud the same issue as before (e.g. VM without floating IP)

So I've increased the timeout to 40s and I've checked on another Jenkins. It seems better, but I will have to redo the test to confirm the fix. I'll try to do that tomorrow or in this evening.

Anyway, I guess that our cloud/network is not in a good health and I suppose that the fix is more a work around.

**Comment by bmoqimi** [comment]
Any luck with the further stages of testing and merging? We are also really counting seconds until this goes live :+1:

**Comment by olivergondza** [comment]
@bmoqimi, waiting for a second user to confirm this is working - @tgatinea appears busy. Can you deploy the snapshot and be the second confirming user? Once we know we have nailed it, I will merge and release.

**Comment by bmoqimi** [comment]
Hi @olivergondza 
I have deployed the snapshot over the weekend and so far it has been working really well. We even see less timeouts on those jenkins instances :+1:
