### ISSUE TITLE
IP allocation over quota in pool Ext-Net., status=403, status-code=FORBIDDEN}

### ISSUE THREAD

**Issue by PhilippeRaven** [jenkinsci/openstack-cloud-plugin#260]
Hello guys,
I'm kind of new in the cloud/openstack world, so maybe I'm just missing a simple thing.

So I get this error :

`ClientResponseException{message=IP allocation over quota in pool Ext-Net., status=403, status-code=FORBIDDEN}`

when I launch a node from jenkins. I can briefly see the instance spawning in Horizon, then it goes deleting and disappears.

If I launch the same instance through Horizon OR via the openstack API (v3) with this line :

`openstack server create --flavor $myflavor --image $myimage --nic net-id=$Ext-Net_pool_id --security-group default --key-name $mykey $instancename`
it launches without problem, takes a public IP and everything works fine.

So I don't understand what can cause the IP Pool problem when it's launched via the openstack-cloud-plugin from jenkins.

Thanks !

**Comment by olivergondza** [comment]
I believe the command alone does not attach the "floating IP" (mind your "fixed IP" might be public based on your OS deployment setup). You can either try reproducing from console by creating a floating IP and assigning it to the server to see if that fails the same way as Jenkins does, or get Jenkins to do what your command does by setting the "Floating IP Pool" option blank.

**Comment by PhilippeRaven** [comment]
Hi Oliver,
thanks for this fast answer :)
You right, if I set the "Floating IP Pool" on "non specified", that works ! I don't know exactly why at the moment, but thanks :)

**Comment by olivergondza** [comment]
Well, floating IPs are a different beast that can be attached to a VM that is a subject to its own quota. You apparently do not need one to work so your deployment has the quota set to 0. Now, when you configure the plugin to allocate one for you, it blows up. Glad this is sorted out for you...

**Comment by PhilippeRaven** [comment]
Well I'll do with this, I have no choice :) The IP is moving each spawn of a new vm, but it's not really a problem.
