### ISSUE TITLE
Provisioning continues even if openstack4j fails

### ISSUE THREAD

**Issue by kpiwko** [jenkinsci/openstack-cloud-plugin#31]
For some reason, the plugin is not able to ssh to the machines. While investigating log, I've found following in jenkins.log:

```
Jan 18, 2016 10:15:18 AM jenkins.plugins.openstack.compute.JCloudsSlaveTemplate get
INFO: Provisioned: NovaServer{id=*masked*, name=openstacknode-161, image={id=*masked*, links=[{href=*masked*, rel=bookmark}]}, flavor=NovaFlavor{id=3, ephemeral=0, swap=0, rxtx_factor=1.0, is_public=true, links=[GenericLink{href=*masked*, rel=bookmark}],
}, status=ERROR, diskconfig=MANUAL, userId=*masked*, created=Mon Jan 18 10:13:03 EST 2016, updated=Mon Jan 18 10:15:18 EST 2016, tenantId=*masked*, hostId=*masked*, addresses=NovaAddresses{addresses={*masked*=[NovaAddress{address=*masked*, type=fixed, version=4, macaddr=*masked*,
}]},
}, powerstate=0, fault=org.openstack4j.openstack.compute.domain.NovaFault@70feb8d5, vmState=error, metadata={jenkins-instance=*masked*}}
```

This is related to 2.0-beta release of the plugin. CC'ing @olivergondza. So, as you can see there was a NovaFault related error - which is not exposed in the log and I guess that if status==ERROR, plugin should quit provisioning all the same.

**Comment by olivergondza** [comment]
Make the log more useful (best effort): https://github.com/gondor/openstack4j/pull/548

**Comment by olivergondza** [comment]
Make the log more useful (best effort): https://github.com/gondor/openstack4j/pull/548

**Comment by olivergondza** [comment]
Make the log more useful (best effort): https://github.com/gondor/openstack4j/pull/548

**Comment by olivergondza** [comment]
Fix proposed.
