### ISSUE TITLE
Document dynamic network selection based on IP utilization

### ISSUE THREAD

**Issue by simkam** [jenkinsci/openstack-cloud-plugin#318]
### Feature Request
Document dynamic network selection based on IP utilization added in https://github.com/jenkinsci/openstack-cloud-plugin/pull/279

**Comment by olivergondza** [comment]
Hey, this is documented in Jenkins config UI. It can also be found on JENKINS_URL/configuration-as-code/reference. For your convenience this is the source https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/plugin/src/main/resources/jenkins/plugins/openstack/compute/SlaveOptions/help-networkId.html

**Comment by simkam** [comment]
cool, thanks! Closing ...
