### ISSUE TITLE
More debugguing doc ? 

### ISSUE THREAD

**Issue by rgarrigue** [jenkinsci/openstack-cloud-plugin#323]
Hi there

It's in between the feature request and call for help: it doesn't work, I don't know why, and I feel like I'm lacking pointers from the doc to see what's happening.

My Openstack cloud is set up, "Test  connection" is ok, the dropdowns in "Slaves options" are filled with relevant informations like Availability Zones and Hardware flavors. I enabled the "FINEST" logs, it doesn't say much

```
...
Started OpenStack slave pre-creation
Jun 14, 2021 1:19:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms
Jun 14, 2021 1:21:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation
Jun 14, 2021 1:21:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms
Jun 14, 2021 1:23:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation
Jun 14, 2021 1:23:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms
Jun 14, 2021 1:25:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Started OpenStack slave pre-creation
Jun 14, 2021 1:25:48 PM FINE jenkins.plugins.openstack.compute.JCloudsPreCreationThread
Finished OpenStack slave pre-creation. 0 ms
...
```

Of course nothing happens in Openstack. Started jobs with no other nodes enabled, nothing start

I manually tested my cloud config in OS just in case, it works. Got no option / button to create an instance out of this cloud just to be sure.  

Tried `Jenkins.instance.clouds[0].openstack.@clientProvider.get()`,  got this answer

> Result: org.openstack4j.openstack.internal.OSClientSession$OSClientSessionV3@4cc64cda

So... what ? What can I do to troubleshoot further ? I guess scripts could help, but I'm not a dev, I don't understand the javadoc

**Comment by rgarrigue** [comment]
One additional question, it seems I should be able to manually create an Openstack Agent. I've been through all the menu, nothing. Am I missing an optional plugin... ?

**Comment by olivergondza** [comment]
The provisioning gets triggered only when there are build in queue targeting label declared by your templates, or you specify minimal number of nodes to be running. I expect lot more to happen in the logs if that ware the case.

Alternatively, one can hit `Provision via OpenStack Cloud Plugin - ???` at "Manage Jenkins > Manage Nodes and Clouds".

**Comment by rgarrigue** [comment]
I did specified a minimal number of nodes. Still nothing happens.

And the button you mentioned behaves like a sorting button. I checked in both firefox and chrome just to be sure. Nothing happens in my browser JS or network consoles

![Peek 28-06-2021 14-45](https://user-images.githubusercontent.com/1872031/123638555-99272f80-d81f-11eb-84b3-21b384b7eef8.gif)

**Comment by olivergondza** [comment]
Hmm, it feels like you do not declared templates at all. See https://github.com/jenkinsci/openstack-cloud-plugin#essentials.

**Comment by rgarrigue** [comment]
Ach... indeed. Thanks for the pointer.

I wish there was something in the UI about this, like a default one you can't remove, or a warning in the logs. It wasn't obvious, since I specified all the options I though I needed in the slaveOptions & co.

@olivergondza should I leave this issue open as a feature request ? Or you're fine with the way it is, hence closing this question ?

**Comment by olivergondza** [comment]
I do not think there is much to do here. There are valid uses of the plugin with no templates configured. And there will be more going forward.
