### ISSUE TITLE
Remove usages of Prototype from OpenStack Cloud

### ISSUE THREAD

**Issue by basil** [jenkinsci/openstack-cloud-plugin#363]
See [this blog post](https://www.jenkins.io/blog/2023/05/12/removing-prototype-from-jenkins/) for details. Prototype will eventually be removed from Jenkins core. To prepare for this transition, this plugin must be migrated away from Prototype. The blog post contains instructions on how to find and eliminate usages of Prototype. In this plugin, the following usages of Prototype have been identified. This may not be an exhaustive list:

```
./plugin/src/main/resources/jenkins/plugins/openstack/compute/JCloudsCloud/computerSet.jelly:23:
new Ajax.Request("${rootURL}/cloud/"+item.value.cloud+"/provision", {
```

CC @olivergondza

**Comment by basil** [comment]
@olivergondza Gentle ping. The replacement of this `Ajax.Request` usage with a call to `fetch()` should be simple to develop and test. Without this fix, this plugin will break when Jenkins core eventually removes Prototype.js.

**Comment by basil** [comment]
@olivergondza Gentle ping

**Comment by olivergondza** [comment]
@basil, thanks for the issues and for the Fix. Merged with a slight amendment.

**Comment by basil** [comment]
Thanks! Can this please be released?
