### ISSUE TITLE
Adding a LICENSE file?

### ISSUE THREAD

**Issue by roitk** [jenkinsci/openstack-cloud-plugin#378]
### Describe your use-case which is not covered by existing documentation.

Hello, I was wondering if it were possible to add a LICENSE to the top level of this repo? I would like to contribute to this project, but I'm not sure what license it falls under. :)

**Comment by olivergondza** [comment]
Good point. Added: https://github.com/jenkinsci/openstack-cloud-plugin/blob/master/LICENSE.

It is great to hear folks are interested in contributing...
