### ISSUE TITLE
Extract cloud / template fields for easier overriding

### ISSUE THREAD

**Issue by olivergondza** [jenkinsci/openstack-cloud-plugin#39]
Some image attributes are now scoped to cloud (`bootTimeout`) and some only to the template (`fsRoot`). It is useful not to repeat oneself and have a possibility to override cloud defaults. (Only `retentionTime` can be overriden at this point.)

To do so, we need to extract the *overridable* properties to separate object to be attached to both cloud and every template. To compute the effective value the most specific value will be used (with rising priority): field default, cloud value, template value. Here is what I suggest:

## Properties of cloud (not overridable)
- `name`
- `identity`
- `credential`
- `endPointUrl`
- `zone`

## Properties of template (not "centralisable")
- `name`
- `labelString`

## Overridable properties
- `retentionTime`
- `startTimeout`
- `floatingIps`
- `imageId`
- `hardwareId`
- `userDataId`
- `numExecutors`
- `jvmOptions`
- `fsRoot`
- `keyPairName`
- `networkId`
- `securityGroups`
- `credentialsId`
- `slaveType`
- `availabilityZone`

I am not sure what to do about `instanceCap`. There is a use-case to spin at most X instances of an image (due to licensing). The best thing I can think of is to have both cloud and template instance cap and provisioning will be aborted as soon as it hits one or the other. This way one can restrict total number of machines provisioned in the wort case and further constrain individual templates when needed. (Note this is not overriding as template can not relax cloud's constrain (unless we will have a special handling for instance cap of course)).

**Comment by winklerm** [comment]
I agree with your proposal regarding the `instanceCap`: we definitely need a total instance cap, while we need to limit particular templates as well. For example, we might need to make sure that one template won't "eat up" all available quota in the cloud preventing jobs requiring a different template from starvation.
