### ISSUE TITLE
Cloud JNLP slave type not working.

### ISSUE THREAD

**Issue by hathoward** [jenkinsci/openstack-cloud-plugin#4]
Using fresh install of Jenkins 1.616 with following plugins:

Windows Slaves Plugin 1.0
Translation Assistance plugin 1.12
Token Macro Plugin 1.10
Subversion Plug-in 2.5
SSH Slaves plugin 1.9
SSH Credentials Plugin 1.11
Script Security Plugin 1.14
SCM API Plugin 0.2
PAM Authentication plugin 1.2
OWASP Markup Formatter Plugin 1.3
Openstack Cloud Plugin 1.7
Maven Integration plugin 2.9
Matrix Project Plugin 1.4.1
Matrix Authorization Strategy Plugin 1.2
MapDB API Plugin 1.0.6.0
Mailer Plugin 1.15
LDAP Plugin 1.11
JUnit Plugin 1.6
Javadoc Plugin 1.3
External Monitor Job Type Plugin 1.4
CVS Plug-in 2.12
Credentials Plugin 1.22
Config File Provider Plugin 2.8.1
Ant Plugin 1.2

Cloud templates set to use JNLP slave launcher do not reflect setting when added as nodes in Jenkins master. No errors pop up in java.util.logging.

**Comment by mavlyutov** [comment]
hi!
its a known behaviour. The JNLP connection according to https://wiki.jenkins-ci.org/display/JENKINS/Distributed+builds is coming alive from slave to master (not master to slave as do ssh connection), so you have two choices:
1. establish connection manually from slave
2. use cloud-init + userScript option in plugin
that userScript should download and launch slave.jar
as for example you could use my:
```(cmd)
    cd "C:\"
    set JENKINS_URL=http://my.jenkins.com
    wget %JENKINS_URL%/jnlpJars/slave.jar
    for /F "tokens=* USEBACKQ" %%F IN (`curl http://169.254.169.254/latest/meta-data/hostname`) DO (
        set HOSTNAME=%%F
    )
    java -jar slave.jar -jnlpUrl %JENKINS_URL%/computer/%HOSTNAME%/slave-agent.jnlp
```

**Comment by hathoward** [comment]
Thank you! Got it working now. Closing issue.
