### ISSUE TITLE
Allow to specify minimum number of slaves to be running for a given template

### ISSUE THREAD

**Issue by AdamSaleh** [jenkinsci/openstack-cloud-plugin#41]
Hi @olivergondza 

we have been successfully using your new version of the plugin in our CI, but the ~1-5 minute startup time of our slaves on our openstack prevent us using this plugin for checking pull requests.

This got us thinking, could you add an option to keep at least a pool of certain size of nodes at all times?

This would probably require two things:
1. when plugin would want to destroy a node, it would need to check not only retention time, but configuration for minimum number of nodes in pool.
2. When number of aviable executors(?) goes below a treshold, plugin would automatically start a new node.

What do you think?

**Comment by olivergondza** [comment]
This is an extension to slave retention strategy that now simply return machine if idle for X minutes. I would like to implement this after https://github.com/jenkinsci/openstack-cloud-plugin/issues/39 so it can be defined per cloud as well as per template.

**Comment by olivergondza** [comment]
Alternatively, I was thinking about a *cumulative idle time* retention strategy: The fewer slaves there are, the longer it will be kept. Once all idle slaves was idle for configured timeout in total, half of them will be released. So when large number of slaves will go idle at about the same time, all of them would wait for further jobs only briefly and pool would be shrink rapidly at the beginning, slowing down as it shrinks, but once the size reaches handful/one machine it will be kept for the whole configured time period. IOW, there would be a guarantee there is at least one slave ready for the configured time period and maybe more if we expect further builds to come.

I like how this adapts to the current load. WDYT?

**Comment by AdamSaleh** [comment]
I would still like to have the mandatory minimum in there :-) But having some superset that would allow for some non-linear retention strategy would be nice addition.

**Comment by imriz** [comment]
This would be a very useful feature...

**Comment by nbartos** [comment]
@olivergondza Have you thought any more about implementing a minimum number of free slaves?  In our environment, the slave bootup time for each job is really problematic.  If several could be launched ahead of the time they are actually needed, it would be a tremendous help.

**Comment by rabadin** [comment]
@olivergondza @AdamSaleh @imriz Hi guys, I had a stab at this: https://github.com/jenkinsci/openstack-cloud-plugin/pull/205. Please have a look when you get a chance.

**Comment by michalxo** [comment]
This issue can be closed as mentioned above @olivergondza .

**Comment by olivergondza** [comment]
Good point. Closing.
