### ISSUE TITLE
Format of username and tenant appears to have swapped around

### ISSUE THREAD

**Issue by jgriffiths1993** [jenkinsci/openstack-cloud-plugin#42]
In the master branch, the `Openstack` constructor expects the username to be:
`<username>` or `<username>/<tenant>`

This used to be:
`<tenant>/<username>`

If we're keeping it this way can we update the help text to show this, or change the format back.

**Comment by olivergondza** [comment]
Thanks, I got the order wrong at least twice. I guess it is time to `// TODO refactor to split tenant:username everywhere including UI`.
