### ISSUE TITLE
SSH port is not configurable

### ISSUE THREAD

**Issue by jpgxs** [jenkinsci/openstack-cloud-plugin#43]
It's obviously an edge case but, for our infra, all of our OpenStack images use a different SSH port from the default 22.

Would be nice if this was configurable per-slavetemplate.

**Comment by olivergondza** [comment]
I would like to refactor the slave type concept into full blown describable so it can host separate options. The reason is the port number is irrelevant for JNLP slaves. The same for *JVM options*.

**Comment by olivergondza** [comment]
Is this still an issue for you?

**Comment by olivergondza** [comment]
The restructure is now ready and adding support for this is trivial. Though, I am putting this on hold until I hear someone is really needs this.
