### ISSUE TITLE
IP allocation over quota in pool

### ISSUE THREAD

**Issue by krissik** [jenkinsci/openstack-cloud-plugin#66]
I have just updated to version 2.1 and I am happy to choose the floating ip pool. But now I get the following error while creating an instance: 

```
javax.servlet.ServletException: ClientResponseException{message=IP allocation over quota in pool public., status=403, status-code=FORBIDDEN}
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
    at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:233)
...
```

I have already 3 floating ips allocated to my openstack tenant (which is my quota for floating ips) but they are not assigned to an instance yet. It would be great if they would be used before trying to allocate a new one. (I am not allowed to allocate/deallocate floating ips)

**Comment by olivergondza** [comment]
I do not think it case much of a harm if we reuse tenant IPs. Some tools, and perhaps even this plugin, can leak them sometimes. So perhaps we should try to reuse before allocating new one.

Todo:

- Make sure we can assign without removing assignment from other machine.
- Throw better exception in case allocation fail.

**Comment by olivergondza** [comment]
@KrissiK, I realized the plugin is trying to deallocate the floating IP (remove it from the tenant) when it deletes the machine. Would that be a problem in your use case?

**Comment by KrissiK** [comment]
Yes - this could be problem because I do not have permissions to allocate and deallocate floationg ips. But I think if it fails silently it would be ok.

**Comment by olivergondza** [comment]
It seems my fears has materialized: http://stackoverflow.com/questions/36497218/assign-openstack-floating-ip-while-making-sure-it-will-not-be-removed-for-other

Let's see if someone suggests something better.

**Comment by olivergondza** [comment]
@KrissiK, I either miss something obvious or your use-case if quite extraordinary. The only safe way to use floating IPs I can see is never reuse allocated FIPs so the mentioned problem can never happen. Did you managed to overcome this somehow for some other automation? If would work out of the box if you have a quota of 3 and permission or allocate/deallocate.

**Comment by KrissiK** [comment]
Well, I am afraid it is extraordinary: I should use my three FIPs so that this IPs can always be traced back to my tenant/project. The mentioned race condition is unlikely (in my case) because I am starting only one instance at once.

**Comment by olivergondza** [comment]
I did not find any best practice on how to reuse FIPs (or how its lifecycle should look like). As what we have to do is prone of hard to debug errors (even though it is safe in your case), I suggest to enable that using custom system property.

**Comment by dgvigil** [comment]
This appears to be the OpenStack API to deallocate a floating IP: http://developer.openstack.org/api-ref-compute-v2.1.html#deleteFloatingIP

**Comment by olivergondza** [comment]
@dgvigil:

> *krissik*: this could be problem because I do not have permissions to allocate and deallocate floationg ips

**Comment by binhex** [comment]
I have a similar situation where i have a limited pool of floating ip's, every time we spin up a new instance via the jenkins openstack plugin it creates a new floating ip from the pool, if the instance is then terminated the floating ip then goes into a "disassociated" state (not released), where the floating ip exists but is no longer is linked to an instance.

If i then spin up another instance the jenkins openstack plugin does not try to re-use the "disassociated" floating ip, but instead creates another floating ip from the pool, if you repeat this process several times you get to a state where the floating ip pool is exausted and you cannot create any more instances.

So the solution to this would be either:-

1. get the jenkins openstack plugin to release the floating ip when it terminates the instance.
2. get the jenkins openstack plugin to re-use any disassociated floating ip's.

see here for a link to somebody posting about the exact same issue, this time with regards to vagrant:-

[](https://github.com/cloudbau/vagrant-openstack-plugin/issues/112)

**Comment by olivergondza** [comment]
@binhex, this is slightly different problem. I [did not find a way to reliably reuse Floating IPs](http://stackoverflow.com/questions/36497218/assign-openstack-floating-ip-while-making-sure-it-will-not-be-removed-for-other) so we should make sure plugin do no leave allocated Floating IPs behind.

**Comment by binhex** [comment]
you are right, the two issues are subtly different, but the solution is the same, either get the jenkins openstack plugin to release floating ip's when the instance is terminated or (in your case as you cant release floating ip's) re-use already generated floating ip's, either solution would work for me.

**Comment by olivergondza** [comment]
@binhex, I have just tested the happy path (delete the slave manually) and the FIP is deallocated correctly. Please turn the [fine logging on](https://wiki.jenkins-ci.org/display/JENKINS/Openstack+Cloud+Plugin#OpenstackCloudPlugin-Accessinglogs) and grep it for dangling FIPs after a while so we know how it can happen. Thanks.

**Comment by olivergondza** [comment]
@binhex, separating the problem as https://github.com/jenkinsci/openstack-cloud-plugin/issues/81.

**Comment by binhex** [comment]
@olivergondza thanks for separating this out, just one last reply to your comment in this thread and then i will use the new issue for all further correspondence, so just to be clear from your comment "I have just tested the happy path (delete the slave manually) and the FIP is deallocated correctly", i do see that the floating ip is "disassociated" when the instance is "terminated" but it is not "released" (as in deleted from the pool), neither is it re-used when a new instance is started, thus you run out of floating ip's very quickly.

**Comment by binhex** [comment]
![screen shot 2016-06-01 at 14 26 26](https://cloud.githubusercontent.com/assets/1121837/15711172/e1441d1c-2804-11e6-8aae-cd4b712b0dca.png)

**Comment by olivergondza** [comment]
> i do see that the floating ip is "disassociated" when the instance is "terminated" but it is not "released"

I observed the exact opposite in my test, release == deallocate in this case. As I said the plugin _does_ that for a long time, though clearly there are code paths where it does not and we need to chase these in #81.

**Comment by olivergondza** [comment]
@krissik, did you have a chance to test latest version with your use-case?
