### ISSUE TITLE
Properly wait for machine to be up before launching

### ISSUE THREAD

**Issue by olivergondza** [jenkinsci/openstack-cloud-plugin#73]
The problem manifests by "No route to host" messages in slave log after the failed launch attempt.
- Do not wait for launch in `#provison` ([dirty](https://github.com/jenkinsci/openstack-cloud-plugin/blob/9fa0b9ce1ddee138db55c96be1a45d406ef83ba0/src/main/java/jenkins/plugins/openstack/compute/JCloudsCloud.java#L299-L309) [hack](https://groups.google.com/d/msg/jenkinsci-dev/UifBMWDkD_o/NtStI8rQCgAJ))
- Wait until the host is reachable (+ service running on given port?). Probably responsibility for the launcher implementation to decide in separate method.

**Comment by olivergondza** [comment]
I am afraid we will have to keep the dirty hack for JNLP nodes (as master may not see those hosts) and even if we manage to detect the host is ready (cloud-init's phone home?) there is no guarantee it will connect in reasonable time (should there be?).

**Comment by empi89** [comment]
This refers to the same issue as https://issues.jenkins-ci.org/browse/JENKINS-34100. The "Startup Timeout" setting seems to be ignored or at least works not like the description suggests:
"Number of milliseconds to wait for the slave node to be accessible via SSH before aborting and retrying. Defaults to 600*1000."

I did not see any retry in the logs and the time I enter does also have no effect on the "no route" error message.

**Comment by olivergondza** [comment]
It seem to be caused by ssh-launcher not retrying in case of "No route to host" but it does for "Connection refused". It needs more investigation.

**Comment by rbabyuk** [comment]
Hi Folks,

I have the same issue.
Jenkins ver. 1.651.1
plugin Openstack Cloud Plugin 2.6

Now I am trying to use JNLP (Swarn plugin preconfigured in openstack template)

**Comment by empi89** [comment]
As a temporary workaround I created a new network within openstack for the slaves. When jenkins master and jenkins slaves are not in the same network the plugin will automatically retry.

**Comment by rbabyuk** [comment]
@empi89 Thanks for update but that haven't helped in my case:
jenkins master: 192.168.200.138
new slave: 192.168.203.5

and all is the same
have I missed anything?

**Comment by empi89** [comment]
Do you have created separate networks that are interconnected with a router? I my setup I have 
ext-net -> int-router -> int-net -> jenkins-master-instance
ext-net -> jenkins-slave-router -> jenkins-slave-net -> jenkins-slaves

The jenkins-slave-router has a connection to the int-net and my jenkins master has a static route entry for jenkins-slave-net via jenkins-slave-router. Does this explanation help?

**Comment by winklerm** [comment]
It affects me as well. The workaround with different networks seems to work for OSP 7, but not for OSP4 (not sure how I could create the networks there).

**Comment by rbabyuk** [comment]
@empi89 Thanks a mil, works fine for me!
~Cheers
Roman

**Comment by amendlik** [comment]
I don't believe this should be tagged as an enhancement, as the plugin used to work, and has been completely unusable for me for months.

**Comment by Tahvok** [comment]
Affecting us as well now. Can't use it because of this issue.

**Comment by lvlie** [comment]
+1, same here which renders it unusable for me, since I cant use jnlp because of "security restrictions"

**Comment by olivergondza** [comment]
Right, I guess it could have worked better before we switched to ssh-slaves plugin. Bug it is.

**Comment by lvlie** [comment]
What would also fix it for me is the possibility for the JNLP connection method to supply a secret as a variable (when using matrix based security with no "agent connect" rights for Anonymous)
As in "java -jar slave.jar -jnlpUrl ${JENKINS_URL}/computer/${HOSTNAME%%.*}/slave-agent.jnlp -secret ${JENKINS_NODE_SECRET}"

**Comment by olivergondza** [comment]
@lvlie, that is known as https://github.com/jenkinsci/openstack-cloud-plugin/issues/104.

**Comment by olivergondza** [comment]
I have reworked waiting for the ssh to be up in https://github.com/jenkinsci/openstack-cloud-plugin/commit/ce78c0bb5587331ce3b33b489ce8e10d5572d2f5, https://github.com/jenkinsci/openstack-cloud-plugin/commit/0da5fb64f4aac75602fb34f80373b0ae0f22540c and https://github.com/jenkinsci/openstack-cloud-plugin/commit/4f57c9cd52bbb0347e81cb45182686885b52f6e2.

I will get it a bit more soaking during holidays and it should be part of the next release.

**Comment by olivergondza** [comment]
Fixed in 2.18
