### ISSUE TITLE
Support for Heat

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#88]
It would be nice if the plugin supported Heat to allocate vm environments for jobs. That declare additional openstack instances.

**Comment by olivergondza** [comment]
I am not sure this makes sense to add to the openstack plugin. What is the use-case?

**Comment by zxiiro** [comment]
Similar to #89 except this uses openstack native support for spinning up a complete integration environment. Our use case is that we have jobs that need to spin up several instances at once before they can perform work and with the current implementation if those instances fail to spin up the job is failed. Using heat we can let openstack handle the spinup of the complete lab environment before letting the job continue.

**Comment by olivergondza** [comment]
Have you tried https://wiki.jenkins-ci.org/display/JENKINS/Openstack+Heat+Plugin?

**Comment by olivergondza** [comment]
I am closing this as there is another plugin where this would fit better.
