### ISSUE TITLE
Move OpenStack plugin configuration to it's own page

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#90]
Similar to plugins like Gerrit Trigger plugin, it would be nice if the OpenStack plugin configuration is own it's own page. We find that all the plugins having configuration inside the global jenkins config page inconvenient and overloads the page.

**Comment by olivergondza** [comment]
That is a valid request for all clouds as they tend to be quite chatty. Needs to be addressed in Jenkins core.

**Comment by olivergondza** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-36341
