### ISSUE TITLE
Job not started

### ISSUE THREAD

**Issue by pmithrandir** [jenkinsci/openstack-cloud-plugin#91]
Hello,

The jenkins version we have will keep the job in pending mode, not starting it because no compatible slave are available.
Actually, it would need to start the job to deploy the node in openstack.

Any way to force the start for cloud node ?

**Comment by olivergondza** [comment]
I do not think I follow. What is the expected vs. actual behavior?

**Comment by pmithrandir** [comment]
Hello.

I expect when I start a job to have it started, then create the openstack slave, then execute the build on this os slave and finally to stop the job.
10 min later to get my os slave destroyed.

What I get is
Job waiting to get an available slot on a compatible slave. 

Ps I run nothing on master maybe that's the reason.

Pierre

**Comment by olivergondza** [comment]
> What I get is
> Job waiting to get an available slot on a compatible slave.

Are there any such slaves provisioned already? Or the plugin does not seem to be creating the slaves? What does log/[cloud statististics](https://wiki.jenkins-ci.org/display/JENKINS/Cloud+Statistics+Plugin) say, is the plugin failing to create the slave or not kicking in at all? What openstack-cloud plugin version are you using? Does the job label match the cloud template (new Jenkins versions report that on job config page)?

> Ps I run nothing on master maybe that's the reason.

That is perfectly fine.

**Comment by pmithrandir** [comment]
Hello,

My apologies, after looing in the logs, I discovered my slave was not installed correctly and that was leading the system to not work at all.

Also, I was adding the slave creation in every jobs whicch was not needed.
The system seems to work today without any issues.

Pierre
