### ISSUE TITLE
It is possible for 2 VMs to spin up with the same name

### ISSUE THREAD

**Issue by zxiiro** [jenkinsci/openstack-cloud-plugin#95]
I think that OpenStack Cloud plugin should check if a name is in use first as I've found a case where it spun up a VM with a duplicate name. Using `nova list` I saw the following on our system:

| a17508d4-5071-40b4-aea2-35c1567fa9f4 | centos7-builder-2022                | ACTIVE | -          | Running     | INSIDE_NET=10.29.10.253 |
| a97a4e42-dfe5-4807-8c4b-a0efac0788b7 | centos7-builder-2022                | ACTIVE | -          | Running     | INSIDE_NET=10.29.11.83  |

**Comment by olivergondza** [comment]
Yeah, I hoped this would be unlikely enough but it does not seems so. I presume it blows up badly on Jenkins side, right?

**Comment by zxiiro** [comment]
Not sure if it was related but we did have Jenkins issues yesterday with our master system. A few jobs hung and several nodes were left undestroyed outside of Jenkins but OpenStack Cloud plugin was no longer managing them so they were in a kind of limbo state.

Actually something that would be handy to have but maybe should be opened as another issue is a page that lists all the VMs the plugin can detect but is not actively managing. We have a sandbox system and one issue we run into on occasion is developers would launch a build but abort it and then while the plugin was trying to destroy the nodes, click abort again causing Jenkins to cancel terminating the nodes thus putting them in limbo state again. It would be nice to have a list of these nodes and maybe a convenient button to destroy them if necessary.

**Comment by olivergondza** [comment]
In the meantime, the server name assignment was reworked to allocate names in sequence skipping those already used eliminating the birthday paradox issue described here.
